### ISSUE TITLE
Investigate button alignment issue

### ISSUE THREAD

**Issue by JoblersTune** [interledger/interledger.org-v4#28]
Investigate button alignment issues that are showing up on only some screens

Should display like this:

![image](https://github.com/user-attachments/assets/6a89acc5-b4a8-4612-a86c-ec9245747bc9)

Sometimes the alignemnt is off:
![image (5)](https://github.com/user-attachments/assets/649ec6c8-c852-4a41-8467-33d73ac6f162)

**Comment by huijing** [comment]
This shouldn't be a thing any more. I fixed it in https://github.com/interledger/interledger.org-v4/commit/b0ce51baed5d4c4d20e800aa287997f3db90192a. If you raised this on Sep 3, it was a cache problem.
